Done Task02: My NUnit
LDVSOFT/spbau-term7-dotnet pull request #4
Opened 2017-10-19 16:35 UTC by LDVSOFT

2017-10-25 19:11 UTC, VMAtm requested changes
На данный момент оценка 4/10 (5/6 за код, 3/4 за тесты, штраф за сдачу после срока)

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner-test/TestRunnerTest.cs
> +namespace net.ldvsoft.spbau.nunit_runner_test
Здесь и далее: пространства имён принято называть с большой буквы, как классы, и без подчёркиваний: `Net.LDVSoft.SPbAU.NUnitRunnerTest`. Так же структура пространств имён обычно повторяет структуру папок в проекте

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner-test/TestRunnerTest.cs
> +        }
Здесь и далее: Можно избежать двойной проверки `is/as`:

            if (ignoredResult is TestIgnored ignored)
            {
                Assert.AreEqual("toBeIgnored", ignored.Reason);
            }
            else
            {
                Assert.Fail($"{nameof(ignoredResult)} isn't the Ignore class");
            }

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner-test/TestRunnerTest.cs
> +        [nunit.BeforeClass]
Можно сделать `using net.ldvsoft.spbau.nunit;` и не писать префикс пространства имён (для `nunit.Test` придётся оставить

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestResult.cs
> +        protected TestRunned(string name, TimeSpan runnedTimeSpan): base(name)
У вас в разных классах по разному стоит двоеточие (нет пробела - есть пробел):

       protected TestRunned(string name, TimeSpan runnedTimeSpan): base(name)
    internal TestSucceeded(String name, TimeSpan runnedTimeSpan) : base(name, runnedTimeSpan)

Обычно просто переносят на новую строку:
        internal TestSucceeded(String name, TimeSpan runnedTimeSpan)
            : base(name, runnedTimeSpan)

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestResult.cs
> +        internal TestSucceeded(String name, TimeSpan runnedTimeSpan) : base(name, runnedTimeSpan)
Почему вы здесь решили использовать полное имя `String`?

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +                from type in assembly.DefinedTypes
Мне кажется, что `extensions` методы проще читать:

assembly.DefinedTypes
                .Where(type => type.GetRuntimeMethods()
                    .Any(method => method.GetCustomAttribute<Test>() != null))
                .Select(RunTestsInClass)
                .ToList();

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +        public static IEnumerable<AssemblyTestsResults> RunTestsInPath(string path)
Здесь можно сэкономить на скобках, поставив `=>`

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +    internal class ClassTestsRunner
У меня ощущение, что вы любите писать на Питоне - пространства имён названы согласно питоновским конвенциям, и вы помещаете разные классы в один. Это не очень хорошая практика. Заведите папку для файлов, которые надо сгруппировать.

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +                                throw new TestDidNotThrowExpectedException(testMethod, test.Expected, e.InnerException);
Количество скобок в этом методе очень большое, согласен. Но для `if` нужно ставить фигурные в любом случае - это было в разборе первого домашнего задания. Более того, кидать исключение для метода только для того, чтобы здесь же его поймать - это плохая практика. Сделайте сразу `return`.

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +                            throw e.InnerException;
В таком пробросе исключения есть минус - вы перетираете stack trace. Лучше просто `throw`

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +                        throw new TestDidNotThrowExpectedException(testMethod, test.Expected, null);
Снова забытые фигурные скобки

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +                return new TestFailed(testMethod.Name, stopwatch.Elapsed, e);
Как уже было сказано, стоит сразу делать `return`. Исключения - для исключений.

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +            foreach (var method in _beforeMethods)
Скобки для `foreach` у вас совсем интересно себя ведут - то они есть, то их нет. Пожалуйста, сделайте так, чтобы они всегда присутствовали

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +                    throw new SetupMethodThrewException(testMethod, _type, method, e);
Тестами не покрыты данные случаи исключений

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +                .Where(method => method.GetCustomAttribute<BeforeClass>() != null))
Почему здесь у вас не LINQ? Не совсем последовательно получается.
Не кажется ли вам, что строка типа `method.GetCustomAttribute<T>() != null)` у вас встречается слишком часто? Почему бы не вынести её в отдельный метод, желательно generic?

            foreach (var method in _type
                .GetRuntimeMethods()
                .Where(CheckAttributeForExistense<BeforeClass>))

        private static bool CheckAttributeForExistense<T>(MethodInfo method)
            where T : BaseAttribute
        {
            return method.GetCustomAttribute<T>() != null;
        }

`BaseAttribute` здесь - это ваш базовый класс для всех аттрибутов - удобный способ отличать свой код от чужого.

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunner.cs
> +            var reports = (
Опять же, на мой взгляд, method chain тут смотрится читабельнее:

            var reports = _type
                .GetRuntimeMethods()
                .Where(CheckAttributeForExistense<Test>)
                .Select(RunTest)
                .ToList();

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunnerExceptions.cs
> +                    suffix = "Instead, it threw nothing.";
Скобки для `if/else`

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunnerMain.cs
> +                    return $"OK (in {res.RunnedTimeSpan})";
Обычно различные `case` отделяют друг от друга пустой строкой

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunnerMain.cs
> +                Console.Out.WriteLine($"Assembly {assemblyResults.Name}:");
Можно просто `Console.WriteLine`

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunnerMain.cs
> +            {
Очень хорошо, что ваша программа проверяет переданные ей аргументы. Хотелось бы видеть ещё и значения по умолчанию (например, их можно сохранить в net.ldvsoft.spbau.nunit-runner --> Properties --> Debug --> Command line arguments. Совсем хорошо было бы видеть там относительный путь.

2017-10-25 19:11 UTC, VMAtm commented on hw2/nunit-runner/TestRunnerMain.cs
> +            var runner = new TestRunner();
Зачем эта переменная?

2017-10-26 08:56 UTC, LDVSOFT commented on hw2/nunit-runner-test/TestRunnerTest.cs
> +        [nunit.BeforeClass]
Я только для единообразия писал именно так.

2017-11-16 20:27 UTC, merged